version: '3.7'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      LOGIN_DB: "postgres"
      PASSWORD_DB: "YuraMarketPassword___1984"
      SECRET_KEY:  "KYKOYAKO"
    depends_on:
      - db

  db:
      image: postgres:13.3
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: "YuraMarketPassword___1984"
      volumes:
         - data:/var/lib/postgresql/data

volumes:
  data: