version: '3.7'
services:

  backend:
    build:
      context: ..
      dockerfile: ./docker/DockerfileBackend
    image: app
    ports:
      - '8000:8000'
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      LOGIN_DB: 'postgres'
      PASSWORD_DB: 'YuraMarketPassword___1984'
      SECRET_KEY:  'KYKOYAKO'
    entrypoint: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8080']
    links:
      - db
    depends_on:
      - db

  db:
      build:
        context: .
        dockerfile: DockerfileDB
      image: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: "YuraMarketPassword___1984"
      volumes:
         - data:/var/lib/postgresql/data

volumes:
  data: